# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0003_auto_20170605_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='introduction_to_models.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '선생')], default='student', max_length=60, verbose_name='이름'),
        ),
    ]
