# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0004_auto_20170606_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '선생')], default='student', max_length=10, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60, verbose_name='이름'),
        ),
    ]
