# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0010_auto_20170607_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='servers_hot_dogs',
            new_name='serves_hot_dogs',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='servers_pizza',
            new_name='serves_pizza',
        ),
    ]
