# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0012_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='class_cls',
            new_name='cls',
        ),
    ]
