# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0015_auto_20170607_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_student_related', related_query_name='introduction_to_models_students', to='introduction_to_models.Car'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_teacher_related', related_query_name='introduction_to_models_teachers', to='introduction_to_models.Car'),
        ),
    ]
